server:
  port: 8005

spring:
  application:
    name: bh
  redis:
    database: 10
    host: 118.31.124.117
    port: 6379
    password: 1q2w3e4r
    timeout: 300ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.129.128:3306/bh?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: bh
    password: Bh1q2w3e4r!!!
  devtools:
    restart:
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jpush:
  message:
    appkey: 52efa0eea8e85ad4cfda034d
    masterSecret: 6a299356b79145984138295f
    tempId: 175585
    signId: 11102
  push:
    appKey: 52efa0eea8e85ad4cfda034d
    masterSecret: 6a299356b79145984138295f

upload:
  uploadPath: ${user.home}/upload/file/
  urlPrefix: https://baidu.com/

